language: cpp
cache:
  directories:
    - $HOME/.ccache
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/build/third_party
sudo: required
dist: trusty
os:
  - linux
addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - git
      - python
      - python-pip
      - python2.7-dev
      - python-wheel
      - clang-format-3.8
      - ccache
notifications:
  email:
    on_success: change
    on_failure: always
