language: cpp
cache:
  directories:
    - $HOME/.ccache
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/build/third_party
sudo: required
dist: trusty
os:
  - linux
addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - git
      - python
      - python-pip
      - python2.7-dev
      - python-wheel
      - clang-format-3.8
      - ccache
      - cmake

script:
    - mkdir -p build
    - cd build && cmake .. && make && make test
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi

notifications:
  email:
    on_success: change
    on_failure: always
